version: '3.9'

networks:
    marketplace-network:
        driver: bridge

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketplace
    ports:
      - 3306:3306
    networks:
      - marketplace-network

  adminer:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: marketplace
    depends_on:
      - db
    ports:
      - 8050:8080
    networks:
      - marketplace-network
